### ISSUE TITLE
创建帐号失败

### ISSUE THREAD

**Issue by 347199174** [SoulLights/SLSocketKit#1]
点击创建帐号显示 OperationalError: (1049, "Unknown database 'sl_socket_kit'")？求解答。。

**Comment by fifyrio** [comment]
你要先有mysql数据库哦，创建一个名字为sl_socket_kit的数据库

**Comment by 347199174** [comment]
共享位置后，地图定位界面是空白，server 和 Xcode 都没报问题，是怎么回事？

**Comment by fifyrio** [comment]
你要先pod安装下，把高德地图插件安装下，试试看哦
